cnn:
  lr: 0.01
  num_epochs: 50
  batch_size: 64
  num_workers: 4
  seed: 42
  epoch_save_freq: 1

mobilenetv2:
  lr: 0.001
  num_epochs: 30
  batch_size: 64
  num_workers: 4
  seed: 42
  epoch_save_freq: 1